agri_school_content = {
    "English": {
        "title": "Welcome to Krishi Pathshala (Agriculture School)📚",
        "description": "Empowering farmers through knowledge.",
        "input_placeholder": "Ask your question here...",
        "surprise_me_button": "Surprise Me!",
        "education_options": (
            "Choosing the Right Crop",
            "Efficient Irrigation",
            "Managing Your Farm Finances",
            "Post-Harvest Handling",
            "Healthy Soil, Healthy Crops",
            "Sustainable Farming Practices",
        ),
        "topic_selection_heading": "##### Or select a topic to learn about:",
        "topic_selection_label": "Select the topic",
        "topic_selection_placeholder": "Choose a topic...",
        "model_response_error": "Sorry, I am unable to answer this question. Please try again later.",
        "spinner_text": "Getting the answer...",
        "error_message": "Please select one category",
    },
    "हिंदी": {
        "title": "कृषि पाठशाला में आपका स्वागत है📚",
        "description": "ज्ञान के माध्यम से किसानों का सशक्तिकरण।",
        "input_placeholder": "अपना प्रश्न यहां पूछें...",
        "surprise_me_button": "मुझे आश्चर्यचकित करें!",
        "education_options": (
            "Choosing the Right Crop",
            "Efficient Irrigation",
            "Managing Your Farm Finances",
            "Post-Harvest Handling",
            "Healthy Soil, Healthy Crops",
            "Sustainable Farming Practices",
        ),
        "topic_selection_heading": "##### या सीखने के लिए एक विषय चुनें:",
        "topic_selection_label": "विषय चुनें",
        "topic_selection_placeholder": "एक विषय चुनें...",
        "model_response_error": "क्षमा करें, मैं इस प्रश्न का उत्तर देने में असमर्थ हूं। कृपया बाद में प्रयास करें।",
        "spinner_text": "उत्तर प्राप्त किया जा रहा है....",
        "error_message": "कृपया एक श्रेणी चुनें",
    },
    "বাংলা": {
        "title": "কৃষি পাঠশালায় আপনাকে স্বাগতম📚",
        "description": "জ্ঞানের মাধ্যমে কৃষকদের ক্ষমতায়ন।",
        "input_placeholder": "আপনার প্রশ্ন এখানে জিজ্ঞাসা করুন...",
        "surprise_me_button": "আমাকে অবাক করুন!",
        "education_options": (
            "Choosing the Right Crop",
            "Efficient Irrigation",
            "Managing Your Farm Finances",
            "Post-Harvest Handling",
            "Healthy Soil, Healthy Crops",
            "Sustainable Farming Practices",
        ),
        "topic_selection_heading": "##### অথবা শেখার জন্য একটি বিষয় নির্বাচন করুন:",
        "topic_selection_label": "বিষয় নির্বাচন করুন",
        "topic_selection_placeholder": "একটি বিষয় নির্বাচন করুন...",
        "model_response_error": "দুঃখিত, আমি এই প্রশ্নের উত্তর দিতে অক্ষম। অনুগ্রহ করে পরে আবার চেষ্টা করুন।",
        "spinner_text": "উত্তর পাওয়া হচ্ছে...",
        "error_message": "অনুগ্রহ করে একটি বিভাগ নির্বাচন করুন",
    },
    "मराठी": {
        "title": "कृषी पाठशाळेत आपले स्वागत आहे 📚",
        "description": "ज्ञानाच्या माध्यमातून शेतकऱ्यांना सक्षम करणे.",
        "input_placeholder": "तुमचा प्रश्न येथे विचारा...",
        "surprise_me_button": "मला आश्चर्यचकित करा!",
        "education_options": (
            "Choosing the Right Crop",
            "Efficient Irrigation",
            "Managing Your Farm Finances",
            "Post-Harvest Handling",
            "Healthy Soil, Healthy Crops",
            "Sustainable Farming Practices",
        ),
        "topic_selection_heading": "##### किंवा शिकण्यासाठी एक विषय निवडा:",
        "topic_selection_label": "विषय निवडा",
        "topic_selection_placeholder": "एक विषय निवडा...",
        "model_response_error": "क्षमस्व, मला या प्रश्नाचे उत्तर देणे शक्य नाही. कृपया नंतर पुन्हा प्रयत्न करा.",
        "spinner_text": "उत्तर मिळवले जात आहे...",
        "error_message": "कृपया एक विभाग निवडा",
    },
}
